### ISSUE TITLE
Refactoring before code paper v1

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-ili#88]
We should refactor and clean the codebase before presentation in the v1 code paper. This issue is to keep a record of all the changes we would like to make. The individual changes will be organized into separate, small PRs, to make it easier to code compare.

Any major removals of code will be preserved in the branch [backup_2023-20-11](https://github.com/maho3/ltu-ili/tree/backup_2023-20-11).

PR #89 
- [x] Remove any temporary scripts from the main branch (e.g. the ones used for private projects).
- [x] Remove the Cosmology object and related tests.
- [x] Make Nicolas' test notebooks consistent with the new version of ltu-ili, or otherwise remove them

PR #90 
- [x] Clean up validation output filenames
- [x] Add ability to specify matplotlib style or kwargs in validation metric plots

PR #91 
- [x] Add TARP error bars (Issue #76)

PR #92 
- [x] Add variational inference posteriors for sbi (Issue #81)

PR #93 
- [x] Update documentation
- [x] Enforce consistent (PEP?) formatting guidelines
- [x] Add a link to a repository of interesting ILI+astro papers

PR #106 
- [x] Add accuracy metric (Issue #104)

PR #122 
- [ ] [This line](https://github.com/maho3/ltu-ili/blob/672b4df8345bd8ddf5ace474b8f8f35aef8f85b8/ili/inference/runner_sbi.py#L382) is missing `posterior_ensemble.name = self.name`
- [x] #117 
- [x] #114

PR #123 
- [ ] Ensure consistency between the pydelfi and sbi versions.
- [x] #119 

TODO:
- [ ] Add train/test splitting in examples
- [ ] Add lampe backend
- [ ] #118

**Comment by maho3** [comment]
Added PR #89  to remove temporary scripts and Cosmology object

**Comment by maho3** [comment]
Added PR #90 to improve and clean up the validation metrics.

**Comment by maho3** [comment]
PR #89  and #90 merged

**Comment by maho3** [comment]
PR #91 merged. Added PR #92 to Add variational inference posteriors
